### PR TITLE
feat: add 'Open Web UI' button to the welcome page

### LINKED ISSUE #763: Add "Open Web UI" to Welcome page
After ipfs-companion is installed we display the welcome page.

When active node is online we say "you are all set" and point at the list of features, but an actionable button to open Web UI would be much more useful:

Thoughts?

### PR DESCRIPTION
**Pull request by colinfruit**
Demo of the proposal in issue #763. Personally, I think that this feature should be included because it provides a quick and obvious way to open the web ui.

closes #763

### CODE REVIEW

**Comment by lidel** [comment]
Thank you @colinfruit! :heart: 

Screen Shot 2019-10-01 at 11 17 51

Before we merge this let's get a quick UX check from @ericronne: 
anything we should tweak in the style of the button?

(this screen is shown when user installs ipfs-companion for the first time and already has ipfs-desktop running in the background)

**Comment by ericronne** [comment]
For accessibility's sake, i'd go with a higher-contrast button/text combo, eg …

Artboard

**Comment by lidel** [comment]
@colinfruit mind swapping the CSS to match Eric's suggestion?
I know you tried to match the style buttons from Web UI but we need to fix contrast there as well, so it is okay to use custom one here for now :)

**Comment by autonome** [comment]
UX recommendation re language - "Web UI" doesn't have meaning for IPFS
users, only for core developers.

Can we change to something descriptive like "View and manage IPFS"? Or
something like that?

**Comment by ericronne** [comment]
That's a little long for a button label.
`Open Dashboard`?

**Comment by colinfruit** [comment]
@lidel, I'm happy to change the CSS to match @ericronne 's suggestions. One question, if 'Open Web UI' isn't descriptive enough for an ordinary user, shouldn't it be changed in both the browser-action drop-down and the welcome screen button? Just asking because it will change the way I go about this. I will just leave the other language's translations as they are, because I don't speak any of the available languages fluently. Is there a proper process handling translations, or anyone I should notify? I prefer 'Open Dashboard' for both, myself.

**Comment by ericronne** [comment]
Yes this is about more than a button label; it’s about what that browser-based thing that’s a lot like IPFS Desktop is called. It’s a branding issue. As such, I recommend that we keep “Open Web UI” as the button text for now – to unblock this PR – and continue the (_important_) naming chat in a new issue.

**Comment by colinfruit** [comment]
OK, 'Open Web UI' it is.

**Pull request merged**
