### PR TITLE
Build Updates

### LINKED ISSUE #677: Switch to  travis-ci.com
IPFS Shipyard recently got access to travis-ci.com and some projects report significant improvements in speed and robustness.

We should switch and compare against currently used Jenkins flow.

Ref. https://github.com/ipfs/aegir/pull/324

### PR DESCRIPTION
**Pull request by lidel**
This PR simplifies Docker-based reproducible build and switches CI to Travis

- [x] fix: switch Docker build to use the `node` user matching UID/GUI of current user at host machine
      (removes the need for writable bit mentioned in #684)
- [x] feat: switch CI to travis-ci.com 
      closes #677 
- [x] feat: enable [codecov](https://codecov.io/gh/ipfs-shipyard/ipfs-companion)

### Known Issues

Windows build is wonky, put it under  `allow_failures` for now.

### CODE REVIEW

**Comment by lidel** [comment]
@hugomrdias [windows build](https://travis-ci.com/ipfs-shipyard/ipfs-companion/jobs/178658259)  breaks silently. 

In raw log, the NVS version looks misaligned –  does this look familiar by any chance?

**Comment by hugomrdias** [comment]
normally it's the cache that breaks, cleaning it fixes the problem but lately not even that. @alanshaw needed to disable cache to make it work in js-ipfs.

**Comment by lidel** [comment]
Turns out Windows build initially failed because companion had a secret defined as `env` variable – see https://github.com/ipfs/aegir/issues/329#issuecomment-465104649
Removed it and the actual build is fixed now. 

CI Build fails at the very end due to travis cache being broken, so I am leaving `windows` in `allow_failures` section until it is fixed upstream.

**Comment by bmwiedemann** [comment]
I'm new to this project, but got plenty experience: it helps to have the reasoning (the part that answers "Why this change?") as part of the individual commits. Issue numbers are a good start, but some textual summaries are better, because issue trackers might be shutdown in some decades but git history can survive longer - and it also has the advantage that it is decentralized and available offline.
And also makes it easier to understand changes without locating the merge commit that brought them in and decoding the github reference to find the description of this PR.

**Comment by lidel** [comment]
@bmwiedemann You are absolutely right. Will pay closer attention to this going forward.

**Pull request merged**
