### PR TITLE
[WIP] Fix popup render issue in Chrome on Mac

### PR DESCRIPTION
**Pull request by lidel**
We need to fix https://github.com/ipfs-shipyard/ipfs-companion/issues/318 on our end, as it is unknown when/if potential fixes will land in Chrome:
- https://bugs.chromium.org/p/chromium/issues/detail?id=728174
- https://bugs.chromium.org/p/chromium/issues/detail?id=730958
- https://bugs.chromium.org/p/chromium/issues/detail?id=457887 (1yr old)
- https://bugs.chromium.org/p/chromium/issues/detail?id=428044 (4yrs old)

I compiled a list of potential workariund to try, starting with the most promising one:
- [x] https://bugs.chromium.org/p/chromium/issues/detail?id=428044#c16 (`requestAnimationFrame`)
- [x] https://bugs.chromium.org/p/chromium/issues/detail?id=428044#c13
- [x] https://github.com/gorhill/uMatrix/issues/423#issuecomment-299214607

@olizilla / @alanshaw   give it a try in a spare moment (I don't have a Mac so it is a stab in a dark 🙃 )

### CODE REVIEW

**Comment by jnthnvctr** [comment]
@lidel  I downloaded the branch and followed the instructions to run the branch in developer mode. 

While it seems like you're much less likely to get into a bad state with the pop up (the first 10 or so tries everything worked great), it does still seem possible to get into a weird state.

So far I've only been able to get into the bad state once (out of the 40 or so times I've clicked on the icon), and that was achieve by clicking repeatedly on the icon in rapid succession: 
image

Every other time its rendered perfectly (like so): 
image

**Comment by olizilla** [comment]
👀

**Comment by olizilla** [comment]
:-( Still there:
screenshot 2018-01-10 17 11 48

**Comment by lidel** [comment]
Rebased  and switched to a workaround from https://github.com/gorhill/uMatrix/issues/423#issuecomment-299214607 – any change now?

**Comment by lidel** [comment]
I see this is one month old: is the issue still present in `master` ?
If yes, does the fix from my last comment (e2f7d02)  help at all?

**Comment by alanshaw** [comment]
I'll take a look now

**Comment by alanshaw** [comment]
@lidel I can't seem to recreate this issue anymore in master. Additionally the [first issue](https://bugs.chromium.org/p/chromium/issues/detail?id=728174) has apparently been fixed. Shall we close this PR and re-open if we notice it again?

**Comment by lidel** [comment]
Yup! Thanks for checking! :+1: 

(reopen if happens again)

**Pull request closed without merging**
