### PR TITLE
fix: IP support on opt-in and opt-out lists

### LINKED ISSUE #944: Can't add an IP address to "Always Disable IPFS Integrations" list.
I have 2 nodes one of which is hosted on a server I can access over VPN.
Attempting to access the remote gateway results in redirection to 127.0.0.1.
"Always Disable IPFS Integrations" list does not accept IP addresses - after clicking off the field the IP address disappears.

Tested in Firefox and Chromium, the behavior is identical.

### PR DESCRIPTION
**Pull request by Sierra410**
fixes #944

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@lidel - might you have time for a review? Thanks!

**Review by lidel — APPROVED** [review]
Thank you @Sierra410! 

ps. I noticed potential problems with IPv6 and inlined custom ports, so I've added additional normalization/tests for those scenarios.

**Comment by Sierra410** [comment]
```js
x => isFQDN(x) || isIP.v4(x) || (!isIP.v6(x) && isIP.v6(x.replace(/[[\]]+/g, '')))
```
This will report malformed IPv6s like ``]::1[`` or ``[:[:[1[`` as valid.

```js
function isHostname(x) {
	if (isFQDN(x) || isIP.v4(x))
		return true
	
	const match = x.match(/^\[(.*)\]$/)
	
	if (match == null)
		return false
	
	return isIP.v6(match[1])
}
```

**Comment by lidel** [comment]
@Sierra410 good catch, mind submitting above in a new PR? :pray:  thanks!

**Pull request merged**
