### PR TITLE
Per-site Redirect Opt-out

### PR DESCRIPTION
**Pull request by lidel**
> This PR aims to:
> - close https://github.com/ipfs-shipyard/ipfs-companion/issues/647 
> - close https://github.com/ipfs-shipyard/ipfs-companion/issues/633

### Icon-based global redirect toggle 

To avoid miss-clicks, confusion, and to disincentivise disabling global redirect, we moved global toggle from Browser Action menu to the utility icon row, and used custom "redirect" icon:

| Enabled  | Disabled |
| ---- | ---- |
| on-2019-01-20--22-59-30 |  | 

> When you start seeing the face above, you cannot unsee it.

### Redirect opt-out per site

- menu item in Active Tab section enables user to disable gateway redirect on current website
- when clicked on regular site toggles redirect for current FQDN and all its subdomains
- when clicked on /ipns/<fqdn>/ (DNSLink) website, toggles redirect for <fqdn>
- after redirect preference changes for current website, the tab is reloaded
- DNSLink websites are reloaded to with URL change between IPNS path and original URL
  > peek 2019-02-20 16-05
  > _Redirect opt-out on DNSLink website loaded from local gateway restores original URL_
- Redirect preference applies not only to request with FQDN of the active tab, but also to all subresource requests that have it in `originUrl` (Firefox) or `Referer` header (Chrome). This means toggle is useful to restore functionality of complex websites such as d.tube (which uses IPFS subresources from various subdomains):
  >  peek 2019-02-20 16-08
  > _Redirect opt-out on regular website: functionality is restored thanks to automatic reload_

#### Opt-out Test URLs

Use below to test the per-site opt-out:

- http://docs.ipfs.io (DNSLink website at `/ipns/docs.ipfs.io`)
- https://d.tube/#!/v/elenasteem/890wiapc (regular website with custom JS)
  - video won't load if redirect is active on initial load
  - disabling redirect for `d.tube` restores playback (note: additional toggle does not impact current video, as data is cached by the website)

### Other
- added subtle animation to utility icons
- global redirect icon will enable integrations if clicked when in suspended state
- menu items specific to the Active Tab are in a section marked with additional border 
  (just a prototype, needs refinement)

## TODO

- [x] fix tests 
- [x] improve UX of "Active Tab" section in browser Action menu
- [x] minimize `redirect-icon.js` (100K right now)
- [x] expose per-site opt-outs as editable field on _Preferences_ screen
  - mvp: one FQDN per line, sort lexicographically
- [ ] remove `requestId` from caches in `onCompleted` || `onErrorOccurred`
- [ ] move use of `browser.*` from browser action page to background page

### CODE REVIEW

**Comment by fsdiogo** [comment]
This is pretty cool @lidel 👌 

In regard to the UI, I'd drop the dashed border as it gives a temporary feeling. [Here's a suggestion](https://www.figma.com/file/anBW8EdVe2bsJhgm6wLk0E3F/ipfs-companion-per-site-redirect?node-id=0%3A1).

One minor UI change: when you hover over the power or redirect toggle, the text always refers to when everything is turned on: `Suspend all IPFS integrations` and `Stop all gateway redirections`, even when it's already suspended or stopped. So I'd say to change to `Toggle all IPFS integrations` and `Toggle all gateway redirections` or something of the like!

**Comment by lidel** [comment]
@fsdiogo thank you, I switched style to follow your suggestion, looks bit cleaner:

> updates-2019-02-23--21-30-03

**Comment by lidel** [comment]
To keep this PR simple, added a textarea on _Preferences_ screen for editing opt-outs:
> 

- Array is converted into multi-line text.
- Entries that are not valid FQDNs are dropped.
- The list is sorted lexicographically.

**Comment by lidel** [comment]
Created some GIFs for README:

> 
> #### Disable Gateway Redirect Per Website
> 
> > _Active Tab_ actions include option to opt-out current website from Gateway redirect of any IPFS subresources.    
> > Disabling redirect for DNSLink website will restore original URL as well:
> >
> > per-site-peek 2019-02-26 00-23    
> 
> #### Disable Gateway Redirect (Global Toggle)
> 
> > A handy toggle to disable all gateway redirects while keeping all other features enabled:
> >
> > redirect
> 
> #### Suspend IPFS Extension
> 
> > The "power" icon can be used to temporarily suspend all IPFS integrations
> > (redirects, API status, content scripts, protocol handlers etc).
> > Useful during testing. Extension can be re-enabled with a single click:
> >
> > screenshot of suspend toggle
> 
> 
>

**Comment by lidel** [comment]
Ok, I think this has been brewing for long enough. 
Would appreciate review or at least some :+1:  or :-1:  on:

- UI presented in https://github.com/ipfs-shipyard/ipfs-companion/pull/687#issuecomment-467243819
- Copy and new strings in [add-on/_locales/en/messages.json](https://github.com/ipfs-shipyard/ipfs-companion/pull/687/files#diff-9714fdee596bf4ac7dd440e6ea65ef09R8)
- Updated copy in [README.md](https://github.com/ipfs-shipyard/ipfs-companion/pull/687/files#diff-04c6e90faac2675aa89e2176d2eec7d8R70) ([preview](https://github.com/ipfs-shipyard/ipfs-companion/blob/feat/redirect-toggle-per-website/README.md#redirect-opt-out))
- **Feedback about the “” icon (used for redirect toggle) is happening in** https://github.com/ipfs-shipyard/ipfs-companion/issues/647#issuecomment-467393961

**Comment by olizilla** [comment]
@lidel in general I'm +1 on the idea. If we borrow from the UI language of IPFS Web UI, then we'd use a small caps label like:

companion-active-tab

Which i think works pretty well

**Comment by olizilla** [comment]
@ericronne I know you have no context for this, but it's would be a useful exercise to talk you through it and get your thoughts.

**Comment by hugomrdias** [comment]
@lidel i made a prototype which packs lots of ideas out of this PR scope

https://codesandbox.io/s/14y8r7qjo3

but basically i like toggle with explicit label and tooltip explaining everything like i'm 5. I prefer label texts that don't change with state.

**Comment by ericronne** [comment]
@olizilla yes, would love a walkthrough! Looks like an interesting workstream; would love to get some context before attempting to lend any sage (ha) advice …

**Comment by lidel** [comment]
Thank you for the feedback!

Summary of changes:
- Menu sections are now separated with webui-like header, as suggested by @olizilla 
- Applied suggestion from @hugomrdias: labels do not change and the state is represented using toggle switch ([@material/switch](https://www.npmjs.com/package/@material/switch))
  - I applied this change to Pin/Unpin as well (it swapped label before)
- Removed "redirect toggle" icon for now, and replace it with regular menu item. 
  - The icon confused a lot of people and @ericronne raised good points about placement and its general shape. 
- Switched to fading-out instead of hiding some inactive elements to reduce UI jitter.


| regular website | dnslink website | offline mode |
| ---- | ---- | ---- |
| 1-github com-2019-03-04--19-16-33 | 1-dnslink-site-2019-03-04--19-18-32 | 1-dnslink-site-off-2019-03-04--19-19-56 |

**Comment by hugomrdias** [comment]
looks awesome !!! 

I would move active tab up and tools down and change "Gateway Redirect" to "Redirect to gateway".

This way both global and tab redirect are together in the UI to create a visual connection between them.

Another option is to change "Redirect on docs.ipfs.io" to "Gateway Redirect on docs.ipfs.io" but this one makes it bigger and with big origins it might get weird.

**Comment by lidel** [comment]
@hugomrdias :ok_hand: 

| regular website | dnslink website | offline mode |
| ---- | ---- | ---- |
| github-2019-03-05--00-32-02 | ipfs-on-2019-03-05--00-32-32 | ipfs-off-2019-03-05--00-33-03 |


I believe it is ready for a test ride in Beta channel.  
Will merge this as-is, we can tweak copy/ux in separate PRs.

**Pull request merged**
