### PR TITLE
feat(ux): suggest ipfs-desktop when no node is found

### PR DESCRIPTION
**Pull request by lidel**
This PR adds info about IPFS Desktop to the welcome page introduced in #565.
The Welcome Screen appears once, after initial install from add-on store.
I also fixed/tweaked some links to give a better onboarding experience.

### Before

TERMINAL OR DIE

### After

Terminal is life, but now there are options for everyone! :^)

fixed-2019-06-03--14-06-27

@olizilla @ericronne  feel free to tweak copy if it can be worded in a  better way.

### CODE REVIEW

**Comment by fsdiogo** [comment]
Wondering if we should switch the order, to push people towards IPFS Desktop?

And then something like `The manual way` with the terminal instructions below.

**Comment by olizilla** [comment]
Good idea @lidel! I shall be getting a TERMINAL OR DIE tattoo, but in the meantime, I'm with @fsdiogo and I think we should promote installing IPFS Desktop to manage your daemon, with the command line as a for experts kinda option.

**Comment by ericronne** [comment]
I love favoring newbies by nudging them toward desktop. The word "daemon" might be too technical for them, too. Perhaps we say, "IPFS does not seem to be running." or something similar for the title, and then offer links to "Get IPFS Desktop" or go the manual/expert route, as @fsdiogo suggests?

**Comment by lidel** [comment]
I moved IPFS Desktop as "the default" way and simplified language:




Thoughts?

**Comment by lidel** [comment]
:+1:  ?

**Pull request merged**
