### PR TITLE
Browser Action popup fixes

### LINKED ISSUE #338: Error while removing IPFS Pin
Removal of a pin triggers an error that lands in Browser Console and is displayed via system notification.
What is interesting is that the _Pin itself is indeed removed_. 
It looks like some kind of race condition or redundant event being yielded.
I did not investigate it deeper, just creating this issue to do it before release.

Below is a log from Firefox (Quick Upload than unPin):

> 2017-12-14-215958_838x431_scrot

I am using go-ipfs v0.4.13/cc01b7f.

### PR DESCRIPTION
**Pull request by lidel**
- closes #338
- as a side-effect this PR may improve situation with #318 
  - I tested in Chrome under Linux and popup never breaks
  - would be great if someone checked under macOS, as we suspect it to be platform-specific
- it should not break anything under Brave, but l'd sleep better if someone confirmed it works there too – would appreciate a quick smoke-test :-)

### CODE REVIEW

**Comment by olizilla** [comment]
👀

**Comment by olizilla** [comment]
Brave: ✅

**Comment by olizilla** [comment]
With some ruthless clicking I still able to get chrome to do the jank render

screenshot 2018-01-09 14 34 09

and I'm kinda proud of this one

screenshot 2018-01-09 14 33 44

but otherwise, all was well. Firefox rendered all smooth and nice no matter how much I clicked and pin/unpin works without error in all.

**Comment by lidel** [comment]
Thanks @olizilla, let's keep #318 open then :)

ps. the last one was glorious!

**Pull request merged**
