### PR TITLE
feat: make Preferences link to docs site

### LINKED ISSUE #595: Fix Readme  links in Preferences screen
Github UI may be intimidating, we probably could use URLs from github pages to improve UX.

### PR DESCRIPTION
**Pull request by jessicaschilling**
- Moves `privacy-policy.md` and `examples` directory to top level; fixes links to privacy policy that result from the move
- Removes `docs` directory; all the remaining content has been moved to docs beta per https://github.com/ipfs/ipfs-docs-v2/pull/182
- Updates all "Read more" links in Companion prefs to point to the appropriate pages on docs-beta.ipfs.io
   - NOTE: These URLs need to be changed once the docs legacy site is deprecated! But, the [deprecation plan](https://github.com/ipfs/docs/issues/475) does include searching all IPFS codebases for instances of "docs-beta" and fixing. Plus redirects.

Closes #595 BUT shouldn't be merged until https://github.com/ipfs/ipfs-docs-v2/pull/182 is merged and docs are in place on the docs site.

**One additional note:** The "Load websites from custom gateway" option still points to https://github.com/ipfs-shipyard/ipfs-companion/issues/667 for its "Learn more" link. @lidel, are you up for writing a brief explainer to put in the docs once that issue is closed (presumably 0.5 release)?

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@lidel, for your reviewing pleasure!

**Comment by lidel** [comment]
- Capitalized `.md` files in the main directory for better discoverability
- Restored `developer-notes.md` and `localization-notes.md` 
  Those things are not useful to regular users, probably will just confuse them, I believe those docs should stay in this repo (see https://github.com/ipfs/ipfs-docs-v2/pull/203)

**Comment by jessicaschilling** [comment]
@lidel -- good idea on capitalization, thanks.
I'd copy-edited all materials brought over to the docs site, so ported those edits back here. Also replaced gifs directory. Please review as you're able -- thank you!

**Comment by jessicaschilling** [comment]
Thanks for all those details!

**Pull request merged**
