### PR TITLE
fix: multi permisison dialogs for the same permission

### PR DESCRIPTION
**Pull request by alanshaw**
Fixes https://youtu.be/k4TMpAXToJc

Permission requests are asynchronous so it's possible for a user to request the same permission multiple times before a response is received. This PR deals with this case.

You can use the following code to check this PR is working:

```js
Promise.all([ipfs.id(), ipfs.id()]).then(console.log).catch(console.log)
```

You should see 2 dialogs in master, and 1 dialog in this branch.

### CODE REVIEW

**Comment by alanshaw** [comment]
@lidel is the issue that the second (and other) dialogs appear blank?

**Comment by lidel** [comment]
Yeah.

**Comment by alanshaw** [comment]
@lidel fix for the issue is here: https://github.com/ipfs-shipyard/ipfs-companion/pull/443

**Comment by lidel** [comment]
@alanshaw  perfect, tested together with #443 works as expected :+1: will merge this shortly.

**Comment by alanshaw** [comment]
🤦‍♂️ sorry, always with the hats

**Pull request merged**
