### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by alanshaw**
Upgrades ipfs, ipfs-api and ipfs-postmsg-proxy

Note this adds `ping`, `pingPullStream` and `pingReadableStream` to the API whitelist

BREAKING CHANGE: See changelog for breaking changes in ipfs https://github.com/ipfs/js-ipfs/blob/master/CHANGELOG.md#0290-2018-05-29

### CODE REVIEW

**Comment by alanshaw** [comment]
@lidel caveat - I haven't had a chance to run this and I wanted to add a test but I haven't had time this week. I'll circle back asap.

**Comment by lidel** [comment]
`ipfs.ping` works fine, and I don't see any regressions elsewhere (uploads, window.ipfs, all good)  :+1: 
I did not test streaming versions of `ping`, but i think tests for that should land in [ipfs-postmsg-proxy](https://github.com/tableflip/ipfs-postmsg-proxy), right?

**Comment by alanshaw** [comment]
@lidel do you mean no callback or an empty `responses` array?

**Comment by lidel** [comment]
@alanshaw looks like no callback (or waiting for timeout). 
Is there anything I can do to provide better context?

**Comment by lidel** [comment]
@alanshaw no callback as far I can tell (or just hanging until timeout?)

**Comment by lidel** [comment]
I tried again with inlined source maps provided by `yarn watch` from `webpack` branch
and was able to confirm the problem is somewhere in libp2p inside of `js-ipfs`.

Sending ping via `wiondow.ipfs` to embedded node:

screenshot_13

ends with "`arr is null`" error in extension background thread (displayed in Browser Console, not the page console):

screenshot_15

**Comment by alanshaw** [comment]
Hey @lidel I was also able to replicate last night. My current theory is that we’re trying to ping old nodes that do not yet have ping implemented. I was going to test to see if I can ping another js-ipfs that I know the version of.

**Pull request merged**
