### PR TITLE
feat: icon in browser action menu upon version update

### PR DESCRIPTION
**Pull request by jessicaschilling**
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/933.

## To do
- [x] Add icon to browser action menu; icon links to latest release notes in new tab
- [x] Make that icon only appear upon first load of new version
- [x] Default "Show Release Notes on Update" in prefs page to off

**Note:** There was discussion in https://github.com/ipfs-shipyard/ipfs-companion/issues/933 about changing the browser bar icon itself in some way to indicate the new version. Suggesting we leave this off (at least for now) - we have significant cube icon mods in https://github.com/ipfs-shipyard/ipfs-companion/issues/662 and I think the cube icon may be "full up" on its ability to convey different states once that issue is implemented.

## Screenshot
image

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Hi @lidel -- is this enough to get started?
Thanks!

**Comment by lidel** [comment]
Thanks! I'll try to wire this up today :crossed_fingers:

**Review by lidel — APPROVED** [review]
LGTM! Thank you @jessicaschilling 

- I've wired it up 
  - Turned out to be more involved than expected, mostly because choo does not support async render functions: I had to calculate show/hide flag in background page and then send it to the popup. 
- Added migration from opt-out to opt-in
- If someone opts-in to opening release notes in a new tab, the redundant notification via icon won't be displayed.

Mind double checking if works as expected?

**Comment by jessicaschilling** [comment]
@lidel -- confirmed everything works as expected in both Chrome and Firefox on Mac. Also saw the same FF visual glitch, and adjusted icons' `viewBox`es to compensate. Mind taking one final look on your end?

**Comment by lidel** [comment]
Look good in Firefox now, thanks!

**Pull request merged**
